# Generated by Django 4.2.3 on 2023-07-15 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='euser',
        ),
    ]
